"""add scenario

Revision ID: 3bf27efa0590
Revises: 3f6e5622ee14
Create Date: 2025-03-30 17:11:48.741054

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bf27efa0590"
down_revision: str | None = "3f6e5622ee14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("timestamp_created", sa.DateTime(), nullable=True),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=True),
        sa.Column("steps", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario")
    # ### end Alembic commands ###
