"""add cpu info

Revision ID: 3f6e5622ee14
Revises: 53125a5ea4a9
Create Date: 2025-03-23 14:23:39.760686

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f6e5622ee14"
down_revision: str | None = "53125a5ea4a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_results", sa.Column("cpu_percent", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("test_results", "cpu_percent")
    # ### end Alembic commands ###
