"""new_test_res

Revision ID: 53125a5ea4a9
Revises: cec5c4d9cd4d
Create Date: 2025-03-23 11:49:53.191981

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53125a5ea4a9"
down_revision: str | None = "cec5c4d9cd4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_results",
        sa.Column("step_description", sa.Text(), nullable=True),
    )
    op.drop_column("test_results", "data_types")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_results", sa.Column("data_types", sa.TEXT(), nullable=True))
    op.drop_column("test_results", "step_description")
    # ### end Alembic commands ###
