"""add docker config

Revision ID: cec5c4d9cd4d
Revises: 04168f60ff07
Create Date: 2025-02-15 19:05:24.705822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cec5c4d9cd4d"
down_revision: str | None = "04168f60ff07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("docker_image", sa.Column("config", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docker_image", "config")
    # ### end Alembic commands ###
